name: "Acceptance stage"

on:
  workflow_call:
    secrets:
      APP_PEM_FILE:
        required: true
      APP_CLIENT_ID:
        required: true
    inputs:
      target_release_version:
        description: "Version of the software, set by the CI/CD pipeline workflow"
        required: false
        type: string
      target_environment:
        description: "Environment being tested"
        required: true
        type: string
      target_account_group:
        description: "Account for the environment being tested"
        required: true
        type: string

jobs:
  environment-set-up:
    name: "Environment set up"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Create infractructure"
        run: |
          echo "Creating infractructure..."
      - name: "Update database"
        run: |
          echo "Updating database..."
      - name: "Deploy application"
        run: |
          echo "Deploying application..."
  test-contract:
    name: "Contract test"
    runs-on: ubuntu-latest
    needs: environment-set-up
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Run contract test"
        run: |
          make test-contract
      - name: "Save result"
        run: |
          echo "Nothing to save"
  test-security:
    name: "Security test"
    runs-on: ubuntu-latest
    needs: environment-set-up
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Run security test"
        run: |
          make test-security
      - name: "Save result"
        run: |
          echo "Nothing to save"
  test-ui:
    name: "UI test"
    runs-on: ubuntu-latest
    needs: environment-set-up
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Run UI test"
        run: |
          make test-ui
      - name: "Save result"
        run: |
          echo "Nothing to save"
  test-ui-performance:
    name: "UI performance test"
    runs-on: ubuntu-latest
    needs: environment-set-up
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Run UI performance test"
        run: |
          make test-ui-performance
      - name: "Save result"
        run: |
          echo "Nothing to save"
  test-integration:
    name: "Integration test"
    runs-on: ubuntu-latest
    needs: environment-set-up
    steps:
      - uses: actions/checkout@v5.0.0
      # Calls out to the nhs-notify-internal repo.
      # The nhs-notify-internal repo will run the tests
      # setup in ./.github/actions/acceptance-tests/action.yaml
      - name: Trigger Acceptance Tests
        shell: bash
        env:
          APP_PEM_FILE: ${{ secrets.APP_PEM_FILE }}
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          TARGET_ENVIRONMENT: ${{ inputs.target_environment }}
          TARGET_ACCOUNT_GROUP: ${{ inputs.target_account_group }}
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --infraRepoName "nhs-notify-digital-letters" \
            --overrideProjectName "nhs" \
            --releaseVersion "${{ inputs.target_release_version || github.head_ref || github.ref_name }}" \
            --targetWorkflow "dispatch-contextual-tests-dynamic-env.yaml" \
            --targetEnvironment "$TARGET_ENVIRONMENT" \
            --targetAccountGroup "$TARGET_ACCOUNT_GROUP" \
            --targetComponent "dl"
  test-accessibility:
    name: "Accessibility test"
    runs-on: ubuntu-latest
    needs: environment-set-up
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Run accessibility test"
        run: |
          make test-accessibility
      - name: "Save result"
        run: |
          echo "Nothing to save"
  test-load:
    name: "Load test"
    runs-on: ubuntu-latest
    needs: environment-set-up
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Run load tests"
        run: |
          make test-load
      - name: "Save result"
        run: |
          echo "Nothing to save"
  environment-tear-down:
    name: "Environment tear down"
    runs-on: ubuntu-latest
    needs:
      [
        test-accessibility,
        test-contract,
        test-integration,
        test-load,
        test-security,
        test-ui-performance,
        test-ui,
      ]
    if: always()
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Tear down environment"
        run: |
          echo "Tearing down environment..."
